---
trigger:
  batch: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/dtspo-10133-reinstate-nagger
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy
  - name: kvConnectedServiceName
    type: string
    default: DCD-CFT-Sandbox

  - name: environment_components
    type: object
    default:
      - deployment: sbox_cnp_dummy_library_test
        environment: sbox
        component: cnp-dummy-library-test
        service_connection: dts-sharedservices-sbox
        dependsOn: Precheck

      - deployment: demo_cnp_dummy_library_test
        environment: demo
        component: cnp-dummy-library-test
        service_connection: dts-sharedservices-demo
        dependsOn: Precheck

      - deployment: ithc_cnp_dummy_library_test
        environment: ithc
        component: cnp-dummy-library-test
        service_connection: dts-sharedservices-ithc
        dependsOn: Precheck

      - deployment: ptlsbox_cnp_dummy_library_test
        environment: ptlsbox
        component: cnp-dummy-library-test
        service_connection: dts-sharedservicesptl-sbox
        dependsOn: Precheck

      - deployment: aat_cnp_dummy_library_test
        environment: stg
        component: cnp-dummy-library-test
        service_connection: dts-sharedservices-stg
        dependsOn: Precheck

      - deployment: perftest_cnp_dummy_library_test
        environment: test
        component: cnp-dummy-library-test
        service_connection: dts-sharedservices-test
        dependsOn: Precheck

variables:
  - name: globalTfCommandOptions
    value: -parallelism=1
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - name: build
    value: $(Build.BuildNumber)
  - name: product
    value: cnp-dummy-library-test
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - stage: Precheck
    jobs:
      - job:
        displayName: Precheck
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-sp-token'
              serviceConnection: ${{ parameters.kvConnectedServiceName }}
              overrideAction: ${{ parameters.overrideAction }}

  - stage: Terraform Nagger Check
    jobs:
      - job:
        displayName: Terraform Nagger
        pool:
          vmImage: ${{ variable.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-version-checker.yaml@cnp-azuredevops-libraries
            parameters:
              serviceConnection: ${{ parameters.kvConnectedServiceName }}

  - ${{ each deployment in parameters.environment_components }}:
      - stage: ${{ deployment.deployment }}
        dependsOn: ${{ deployment.dependsOn }}
        jobs:
          - job: TerraformPlanApply
            displayName: ${{ deployment.environment }} - terraform ${{ parameters.overrideAction }}
            pool:
              vmImage: ${{ variables.agentPool }}
            timeoutInMinutes: ${{ variables.timeoutInMinutes }}
            steps:
              - template: steps/terraform.yaml@cnp-azuredevops-libraries
                parameters:
                  overrideAction: ${{ parameters.overrideAction }}
                  environment: ${{ deployment.environment }}
                  component: ${{ deployment.component }}
                  kvConnectedServiceName: ${{ parameters.kvConnectedServiceName }}
                  serviceConnection: ${{ deployment.service_connection }}
                  terraformInitSubscription: ${{ variables.terraformInitSubscription }}
                  product: ${{ variables.product }}
                  planCommandOptions: ${{ variables.globalTfCommandOptions }}
                  applyCommandOptions: ${{ variables.globalTfCommandOptions }}
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }}
